<h1><?php echo $this->escapeHtml($this->title); ?></h1>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action',$this->url('entidades',array('controller' => 'index', 'action'=>'guardar')));
$form->setAttribute('method','post');

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idEntidad'));
?>
<div class="form_element">
    <?php
    $nombre = $form->get('nombre');
    echo $formLabel->openTag() . $nombre->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($nombre);
    echo $this->formElementErrors($nombre);
?></div>
<div class="form_element">
    <?php
    $direccion = $form->get('direccion');
    echo $formLabel->openTag() . $direccion->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($direccion);
    echo $this->formElementErrors($direccion);
?></div>
<div class="form_element">
    <?php
    $lugar = $form->get('lugar');
    echo $formLabel->openTag() . $lugar->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($lugar);
    echo $this->formElementErrors($lugar);
?></div>
<div class="form_element">
    <?php
    $telefono = $form->get('telefono');
    echo $formLabel->openTag() . $telefono->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($telefono);
    echo $this->formElementErrors($telefono);
?></div>
<div class="form_element">
    <?php
    $email = $form->get('email');
    echo $formLabel->openTag() . $email->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($email);
    echo $this->formElementErrors($email);
?></div>
<div class="form_element">
    <?php
    $facebook = $form->get('facebook');
    echo $formLabel->openTag() . $facebook->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($facebook);
    echo $this->formElementErrors($facebook);
?></div>
<div class="form_element">
    <?php
    $twitter = $form->get('twitter');
    echo $formLabel->openTag() . $twitter->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($twitter);
    echo $this->formElementErrors($twitter);
?></div>
    
<?php echo $this->formElement($form->get('send')) ?>
<?php echo $this->form()->closeTag() ?>