<div id="modelo_footer_wrapper">

	<div id="modelo_footer">
    	
        <div class="section_w180">
        	<div class="header_05">Servicios</div>
            <div class="section_w180_content"> 
            	<ul class="footer_menu_list">
                    <li><a href="#">Servicio ofrecido uno</a></li>
                    <li><a href="#">Servicio ofrecido dos</a></li>
                    <li><a href="#">Servicio ofrecido tres</a></li>
                    <li><a href="#">Servicio ofrecido cuatro</a></li>
                </ul>
			</div>
        </div>
        
        <div class="section_w180">
        	<div class="header_05">Sobre nosotros</div>
            <div class="section_w180_content">
                <ul class="footer_menu_list">
                    <li><a href="#">Quiénes somos</a></li>
                    <li><a href="#">Dónde estamos</a></li>
                    <li><a href="#">Un poco de historia</a></li>                
                </ul>
            </div>
        </div>
                
        <div class="section_w180">
        	<div class="header_05">Enlaces de interés</div>
            <div class="section_w180_content"> 
                <ul class="footer_menu_list">
                    <li><a href="#">Enlace uno</a></li>
                    <li><a href="#">Enlace dos</a></li>
                    <li><a href="#">Enlace tres</a></li>             
                </ul>
			</div>
        </div>
        
        <div class="section_w180">
	        <div class="header_05">Contacto</div>
            
            <div class="section_w180_content">
            
                <ul class="footer_menu_list">
                    <li><a href="#">Teléfono este</a></li>
                    <li><a href="#">Correo electrónico</a></li>           
                </ul>
			</div>
        </div>

        <div class="section_w180">
	        <div class="header_05">Ingreso</div>
            
            <div class="section_w180_content">
            
                <ul class="footer_menu_list">
                    <li><a href="#">Ingreso al Sistema</a></li>
                </ul>
            </div>
        </div>
            
        <div class="margin_bottom_20"></div>
        Copyright © 2014 <a href="#">AC - CF</a> | <a href="http://www.alboradasoft.com.mx" target="_parent">Orgullosamente Tabasqueños</a>
        <div class="cleaner"></div>
    </div> <!-- fin de footer -->
</div> <!-- fin de footer -->
<div align=center>AC - CF <a href='http://www.alboradasoft.com.mx'>Aplicaciones web</a></div>
