<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <?php echo $this->headMeta()->setCharset('UTF-8')?>
        <?php echo $this->headTitle('') ?>
        <?php echo $this->headLink()->prependStylesheet($this->basePath().'/css/style.css')?>
        <?php echo $this->headStyle()?>
        <?php echo $this->headScript()->prependFile($this->basePath().'/js/jquery.min.js')?>
    </head>
    <body style="background-image:url(<?php echo $this->basePath().'/img/pages/404.jpg' ?>); 
          background-size:1350px 620px" >
            
            <?php echo $this->partial('layout/header'); ?>
        
        <div class="content404">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <div class="content404_2">
            <p></p>
        </div> <!-- /container -->
        
        <?php echo $this->partial('layout/footer'); ?>
    </body>
</html>
