<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <?php echo $this->headMeta()->setCharset('UTF-8')?>
        <?php echo $this->headTitle('') ?>
        <?php echo $this->headLink()->prependStylesheet($this->basePath().'/css/style.css')?>
        <?php echo $this->headStyle()?>
        <?php echo $this->headScript()->prependFile($this->basePath().'/js/jquery.min.js')?>
    </head>
    <body>
<!--                <img src="<?php echo $this->basePath().'/img/pages/home.png' ?>" border="0"> -->
            
        <?php echo $this->partial('layout/header'); ?>
        
        <?php if($this->layout()->mensaje !== null): ?>
            <div id="mensaje" style="color:
            <?php echo $this->layout()->colorMensaje? $this->layout()->colorMensaje: "red"; ?>; 
            font-weight:bold; margin:20px;">
                <?php echo $this->mensaje; ?>
            </div>
        <?php endif; ?>
        
        <div class="content">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        
        <?php echo $this->partial('layout/footer'); ?>
        
    </body>
</html>
