<?php
$this->headTitle($this->title);
?>
<h1> <?php echo $this->escapeHtml($this->title); ?></h1>
<p>
    <a href="<?php echo $this->url('obras', array('controller' => 'tipo-obra',
        'action' => 'crear')); ?>">nuevo tipo de obra (+)</a>
</p>
<table class="table">
    <tr>
        <th>Id tipo de obra</th>
        <th>Descripción</th>
        <th>Editar</th>
        <th>Eliminar</th>
    </tr>
    <?php foreach ($this->tipoObra as $tipo):?>
        <tr style="background-color:<?php echo $this->cycle(array("#C0F0F0",
                                                            "#FFFFFF"))
                                              ->next()?>">
            <td><?php echo $tipo->getIdtipoObra() ?></td>
            <td><?php echo $this->escapeHtml($tipo->getDescripcion()) ?></td>
            <td>
                <a href="<?php echo $this->url('obras',array('controller' => 'tipo-obra',
                    'action' => 'editar', 'id' => $tipo->getIdtipoObra())) ?>">Editar</a>
            </td>
            <td>
                <a onclick="return confirm('¿Está seguro que desea eliminar a <?php 
                echo $tipo->getDescripcion() ?>? ');"
                        href="<?php echo $this->url('obras', array('controller' => 
                            'tipo-obra','action' => 'eliminar','id' => $tipo->getIdtipoObra())) ?> ">Eliminar</a>
            </td>
            
        </tr>
    <?php endforeach; ?>
<?php 
$this->cycle()->assign(array("#C0F0F0","#FFFFFF"));
$this->cycle()->prev();
?>
        
</table>

