<div id="modelo_banner_wrapper">
	<div id="modelo_banner">
    
    	<div id="modelo_banner_image">
        	<div id="modelo_banner_image_wrapper">
            	<img src="<?php echo $this->basePath().'/img/pages/logoFT.jpg' ?>" alt="Logo" />
            </div>
        </div>
        
        <div id="modelo_banner_content">
        	<div class="header_01">Bienvenidos al Fondo </div>
            <p>Un pequeño recorrido de lo que ofrece nuestro Estado en materia cultural. </p>
            <div class="button_01"><a href="#">Conócenos</a></div>
        </div>	
    
    	<div class="cleaner"></div>
    </div> <!-- fin de banner -->
</div> <!-- fin de banner wrapper -->

<div id="modelo_content_wrapper">
	<div id="modelo_content">
    
    	<div id="column_w530">
        	
            <div class="header_02">Fondo Tabasco Virtual</div>
            
            <p class="em_text">Un texto relacionado con lo que ofrece el Fondo Tabasco, luego un enlace al <a href="http://www.iec.tabasco.gob.mx/" target="_parent">Instituto Estatal de Cultura</a> para conocer más.</p>
            
            <p>Otro texto que explica algo más del Fondo Tabasco.</p>
            
            <div class="margin_bottom_20"></div>
            
            <ul class="content_list_01">
                <li>Un enlace relacionado con el <a href="http://iec.tabasco.gob.mx/content/parque-museo-de-la-venta" target="_parent">Parque Museo La Venta</a>.</li>
                <li>Más información pertinente con el Fondo Tabasco.</li>
            </ul>
            
            <div class="margin_bottom_20"></div>
            
            <div class="content_section_01">
            	Esta Galería acoge las obras que integran la Colección Tabasco, que se integra con obras de artistas plásticos locales, nacionales e internacionales que han expuesto en Tabasco y donado una obra para conformar este patrimonio cultural.
            </div>
            
            <div class="cleaner"></div>
        </div>
        
        <div id="column_w300">
        
        	<div class="header_03">Temas de interés</div>
            
            <div class="column_w300_section_01">
            	<div class="news_image_wrapper">
                	<img src="<?php echo $this->basePath().'/img/pages/img001.jpg' ?>" alt="image" />
                </div>
                
                <div class="news_content">
                	<div class="news_date">Nov 29, 2014</div>
                    <div class="header_04"><a href="#">Que nadie se quede callado</a></div>
                    <p>Presentamos aquí la nueva obra adquirida en el Fondo, su nombre: Collage.</p>
				</div>
                                
                <div class="cleaner"></div>
            </div>
            
            <div class="column_w300_section_01 even_color">
            	<div class="news_image_wrapper">
                	<img src="<?php echo $this->basePath().'/img/pages/img002.jpg' ?>" alt="image" />
                </div>
                
                <div class="news_content">
                	<div class="news_date">Dic 18, 2014</div>
                    <div class="header_04"><a href="#">Noticias</a></div>
                    <p>Esta semana rescataremos diversas obras artísticas, la cuales estarán en exposición en el Fondo.</p>
				</div>
                                
                <div class="cleaner"></div>
            </div>
            
            <div class="column_w300_section_01">
            	<div class="news_image_wrapper">
                	<img src="<?php echo $this->basePath().'/img/pages/img003.jpg' ?>" alt="image" />
                </div>
                
                <div class="news_content">
                	<div class="news_date">OCT 15, 2014</div>
                    <div class="header_04"><a href="#">Obra del mes</a></div>
                    <p>Esta obra ha sido elegida como la obra del mes por los conocedores.</p>
				</div>
                                
                <div class="cleaner"></div>
            </div>
            
            <div class="cleaner"></div>
        </div>
    
    	<div class="cleaner"></div>
    </div> <!-- fin de content wrapper -->
</div> <!-- fin de content wrapper -->
 
<div class="menu">
    <h2 class="panel-title"><?php echo $this->titulo ?></h2>

    <div>
    <p>Para ir al módulo de artistas:</p>
    <p><a href="<?php echo $this->url('artistas', array('controller' => 'index',
        'action' => 'index')); ?>">Listado de los artistas</a></p>
    </div>
    <div>
        <p>Para ir al módulo de entidades:</p>
        <p><a href="<?php echo $this->url('entidades', array('controller' => 'index',
            'action' => 'index')); ?>">Listado de las entidades que solicitan obras</a></p>
    </div>
    <div>
    <p>Para ir al módulo de obras:</p>
    <p><a href="<?php echo $this->url('obras', array('controller' => 'obras',
        'action' => 'index')); ?>">Listado de las obras</a></p>
    <p><a href="<?php echo $this->url('obras', array('controller' => 'index',
        'action' => 'index')); ?>">Listado de los estilos de las obras</a></p>
    
    <p><a href="<?php echo $this->url('obras', array('controller' => 'tipo-obra',
        'action' => 'index')); ?>">Listado de los tipos de obra</a></p>
    </div>
    <div>
        <p>Para ir al módulo de préstamos</p>
        <p><a href="<?php echo $this->url('prestamos', array('controller' => 'index',
        'action' => 'index')); ?>">Listado de los préstamos</a></p>
    </div>
</div>

