 
<div class="menu">
    <h2 class="panel-title"><?php echo $this->titulo ?></h2>

    <div>
    <p>Para ir al módulo de artistas:</p>
    <p><a href="<?php echo $this->url('artistas', array('controller' => 'index',
        'action' => 'index')); ?>">Listado de los artistas</a></p>
    </div>
    <div>
        <p>Para ir al módulo de entidades:</p>
        <p><a href="<?php echo $this->url('entidades', array('controller' => 'index',
            'action' => 'index')); ?>">Listado de las entidades que solicitan obras</a></p>
    </div>
    <div>
    <p>Para ir al módulo de obras:</p>
    <p><a href="<?php echo $this->url('obras', array('controller' => 'obras',
        'action' => 'index')); ?>">Listado de las obras</a></p>
    <p><a href="<?php echo $this->url('obras', array('controller' => 'index',
        'action' => 'index')); ?>">Listado de los estilos de las obras</a></p>
    
    <p><a href="<?php echo $this->url('obras', array('controller' => 'tipo-obra',
        'action' => 'index')); ?>">Listado de los tipos de obra</a></p>
    </div>
    <div>
        <p>Para ir al módulo de préstamos</p>
        <p><a href="<?php echo $this->url('prestamos', array('controller' => 'index',
        'action' => 'index')); ?>">Listado de los préstamos</a></p>
    </div>
</div>

<p>Sistema de registro de autores, obras y préstamos.</p>
